### **Taller 1 - Histogramas**

#### **Integrantes**

- Oscar Leonardo Riveros Perez

- Yovany Esneider Vargas Gutierrez

**a. Implementacion del Algoritmo de adelgazamiento**

In [168]:
import cv2
from IPython.display import Image
import numpy as np

from matplotlib import pyplot as plt
from prettytable import PrettyTable 


## pip install prettytable 
Mano_light  =   cv2.imread('Images/Img_Light_1.png',1)
Mano_shadow =   cv2.imread('Images/Img_Outdoor_1.png',1)
Mano        =   cv2.imread('Images/Img_Indoor_1.png',1)

Mano_light_Gray  =   cv2.imread('Images/Img_Light_1.png',0)
Mano_shadow_Gray =   cv2.imread('Images/Img_Outdoor_1.png',0)
Mano_Gray        =   cv2.imread('Images/Img_Indoor_1.png',0)


In [189]:
def Adelgazamiento(Imagen,Estructurante):
    Hit_Miss=cv2.morphologyEx(Imagen,cv2.MORPH_HITMISS,Estructurante)
    return (Imagen-Hit_Miss)

def Adelgazamiento_Multiple(Imagen,Array):

    result=Adelgazamiento(Imagen,Array[0])
    for i in Array[1:]:
        result=Adelgazamiento(result,i)

    return result


test=np.array(([0,0,0,0,0,0,0,0,0,0,0,0,0],
               [0,1,1,1,1,1,1,1,1,1,1,1,0],
               [0,1,1,1,1,1,1,1,1,1,0,0,0],
               [0,1,1,1,1,1,1,1,1,1,0,0,0],
               [0,1,1,1,1,1,1,1,1,1,0,0,0],
               [0,1,1,1,0,0,1,1,1,1,0,0,0],
               [0,0,0,0,0,0,0,0,0,0,0,0,0]),
               dtype='uint8')
test=test*255

Est_1=np.array(([-1,-1,-1],
                [0,1,0],
                [1,1,1]),
                dtype='int')

Est_2=np.array(([0,-1,-1],
                [1,1,-1],
                [1,1,0]),
                dtype='int')

Est_3=np.array(([1,0,-1],
                [1,1,-1],
                [1,0,-1]),
                dtype='int')

Est_4=np.array(([1,1,0],
                [1,1,-1],
                [0,-1,-1]),
                dtype='int')

Est_5=np.array(([1,1,1],
                [0,1,0],
                [-1,-1,-1]),
                dtype='int')

Est_6=np.array(([0,1,1],
                [-1,1,1],
                [-1,-1,0]),
                dtype='int')

Est_7=np.array(([-1,0,1],
                [-1,1,1],
                [-1,0,1]),
                dtype='int')

Est_8=np.array(([-1,-1,0],
                [-1,1,1],
                [0,1,1]),
                dtype='int')

result=Adelgazamiento_Multiple(test,[Est_1,Est_3,Est_4,Est_5,Est_6,Est_7,Est_8,Est_1,Est_4,Est_6,Est_6])


print(result)

#https://alojamientos.us.es/gtocoma/pid/tema5-1.pdf
#https://theailearner.com/tag/hit-or-miss-transformation-opencv/
#https://docs.opencv.org/4.x/db/d06/tutorial_hitOrMiss.html


[[  0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0 255   0   0   0   0   0   0   0 255 255 255   0]
 [  0 255 255   0   0   0   0   0 255 255   0   0   0]
 [  0   0 255 255 255 255 255 255 255   0   0   0   0]
 [  0 255 255   0   0   0   0   0 255   0   0   0   0]
 [  0 255   0   0   0   0   0   0 255 255   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0]]


**b. Implementacion del Algoritmo de esqueleto**

**c. Funciones vistas en el taller**