### **Taller 1 - Histogramas**

#### **Integrantes**

- Oscar Leonardo Riveros Perez

- Yovany Esneider Vargas Gutierrez

**a. Implementacion del Algoritmo de adelgazamiento**

In [41]:
import cv2
from IPython.display import Image
import numpy as np
from matplotlib import pyplot as plt
from prettytable import PrettyTable 


## pip install prettytable 
Mano_light  =   cv2.imread('Images/Img_Light_1.png',1)
Mano_shadow =   cv2.imread('Images/Img_Outdoor_1.png',1)
Mano        =   cv2.imread('Images/Img_Indoor_1.png',1)

Mano_light_Gray  =   cv2.imread('Images/Img_Light_1.png',0)
Mano_shadow_Gray =   cv2.imread('Images/Img_Outdoor_1.png',0)
Mano_Gray        =   cv2.imread('Images/Img_Indoor_1.png',0)


In [76]:
def Adelgazamiento(Imagen,Estructurante):
    Hit_Miss=(np.logical_and(cv2.erode(Imagen,Estructurante,1),cv2.erode(~Imagen,~Estructurante,1)))
    # Hit_Miss=cv2.morphologyEx(Imagen,cv2.MORPH_HITMISS,Estructurante)

    return (np.logical_and(Imagen,~Hit_Miss)).astype('uint8')


test=np.array([[1,1,1,1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1,1,0,0],[1,1,1,1,1,1,1,1,1,0,0],[1,1,1,1,1,1,1,1,1,0,0],[1,1,1,0,0,1,1,1,1,0,0]]).astype('uint8')
Est=np.array([[0,0,0],[0,1,0],[1,1,1]]).astype('uint8')

xd=Adelgazamiento(test,Est)
# print((test))
print(xd)



# print(cv2.getStructuringElement(cv2.MORPH_CROSS,(7,7),(-1,-1)))


[[1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 0 0]
 [1 1 1 1 1 1 1 1 1 0 0]
 [1 1 1 1 1 1 1 1 1 0 0]
 [1 1 1 0 0 1 1 1 1 0 0]]


**b. Implementacion del Algoritmo de esqueleto**

**c. Funciones vistas en el taller**