### **Taller 6 -  Clasificación con RNA**

#### **Integrantes**

- Oscar Leonardo Riveros Perez

- Yovany Esneider Vargas Gutierrez 

**1. Estudiar el uso de Redes Neuronales en scikit-learn, haciendo énfasis en la función MLPClassifier**

**a. Machine Learning con redes neuronales usando scikit-learn y su func**

In [298]:
# Paso 1 - Carga de librerías y módulos necesarios
# Librerías
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import sklearn
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor
# Módulos
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, classification_report, confusion_matrix
from math import sqrt

In [299]:
# Paso 2 - Lectura de datos y comprobación
df = pd.read_csv('diabetes.csv')
print(df.shape)
df.describe().transpose()


(768, 9)


count        mean         std     min       25%       50%  \
pregnancies  768.0    3.845052    3.369578   0.000   1.00000    3.0000   
glucose      768.0  120.894531   31.972618   0.000  99.00000  117.0000   
diastolic    768.0   69.105469   19.355807   0.000  62.00000   72.0000   
triceps      768.0   20.536458   15.952218   0.000   0.00000   23.0000   
insulin      768.0   79.799479  115.244002   0.000   0.00000   30.5000   
bmi          768.0   31.992578    7.884160   0.000  27.30000   32.0000   
dpf          768.0    0.471876    0.331329   0.078   0.24375    0.3725   
age          768.0   33.240885   11.760232  21.000  24.00000   29.0000   
diabetes     768.0    0.348958    0.476951   0.000   0.00000    0.0000   

                   75%     max  
pregnancies    6.00000   17.00  
glucose      140.25000  199.00  
diastolic     80.00000  122.00  
triceps       32.00000   99.00  
insulin      127.25000  846.00  
bmi           36.60000   67.10  
dpf            0.62625    2.42  
age           41.00000   81.00  
diabetes       1.00000    1.00

In [300]:
# Paso 3 - Creación de arreglo de características y variable de respuesta
target_column = ['diabetes']

predictors = list(set(list(df.columns))-set(target_column))  #Lista con todos los encabezados menos 'diabetes'
df[predictors] = df[predictors]/df[predictors].max()
df.describe().transpose()

count      mean       std       min       25%       50%  \
pregnancies  768.0  0.226180  0.198210  0.000000  0.058824  0.176471   
glucose      768.0  0.607510  0.160666  0.000000  0.497487  0.587940   
diastolic    768.0  0.566438  0.158654  0.000000  0.508197  0.590164   
triceps      768.0  0.207439  0.161134  0.000000  0.000000  0.232323   
insulin      768.0  0.094326  0.136222  0.000000  0.000000  0.036052   
bmi          768.0  0.476790  0.117499  0.000000  0.406855  0.476900   
dpf          768.0  0.194990  0.136913  0.032231  0.100723  0.153926   
age          768.0  0.410381  0.145188  0.259259  0.296296  0.358025   
diabetes     768.0  0.348958  0.476951  0.000000  0.000000  0.000000   

                  75%  max  
pregnancies  0.352941  1.0  
glucose      0.704774  1.0  
diastolic    0.655738  1.0  
triceps      0.323232  1.0  
insulin      0.150414  1.0  
bmi          0.545455  1.0  
dpf          0.258781  1.0  
age          0.506173  1.0  
diabetes     1.000000  1.0

In [301]:
# Paso 4 - Creación de los conjuntos de entrenamiento y prueba

X = df[predictors].values
y = df[target_column].values

# 30% datos de prueba y 70% datos de entrenamiento
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30, random_state = 40)
print(X_train.shape)
print(X_test.shape)

(537, 8)
(231, 8)


In [302]:
# Paso 5 - Construcción, Predicción, y evaluación del modelo de red neuronal
# Se utiliza la función de activación lineal rectificada y un limite de 500 iteraciones

mlp = MLPClassifier(hidden_layer_sizes = (8,8,8), activation = 'relu', solver = 'adam', max_iter = 500)     #Red neuronal con 3 capas de neuronas ocultas con 8 neuronas en cada una
mlp.fit(X_train,y_train)
predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

c:\Users\metal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1105: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [303]:
# Resultados de entrenamiento
print(confusion_matrix(y_train,predict_train))
print(classification_report(y_train,predict_train))

[[320  38]
 [ 76 103]]
              precision    recall  f1-score   support

           0       0.81      0.89      0.85       358
           1       0.73      0.58      0.64       179

    accuracy                           0.79       537
   macro avg       0.77      0.73      0.75       537
weighted avg       0.78      0.79      0.78       537



In [304]:
# Resultados de prueba
print(confusion_matrix(y_test,predict_test))
print(classification_report(y_test,predict_test))

[[126  16]
 [ 40  49]]
              precision    recall  f1-score   support

           0       0.76      0.89      0.82       142
           1       0.75      0.55      0.64        89

    accuracy                           0.76       231
   macro avg       0.76      0.72      0.73       231
weighted avg       0.76      0.76      0.75       231



Las 2 medidas relevantes es la precisión y la Puntuación F1, esta ultima vide el desempeño entre la precisión y la sensibilidad (recall), lo ideal es que estás dos sean 1. Sin embargo, es difícil de obtener en escenarios del mundo real, por ahora la red neuronal formada por un perceptron multi capas (MLP), presenta un desempeño superior al 70%, sin embargo, presenta un mejor comportamiento en los casos negativos de diabetes.

**2. Clasificador, cuando son aplicadas al conjunto de vectores de características del proyecto**

Los datos a trabajar surgen de la extracción de 30 características, de las imágenes, sin embargo se somete a un análisis PCA para optimizar dicha base de datos, en este caso se reduce una dimensión y se añade un dato adicional el cual corresponde a el resultado esperado.

In [323]:
# Lectura de datos y comprobación
df = pd.read_csv('Project_Data_Fingers.csv')
print(df.shape)
df.describe().transpose()

(343, 30)


count          mean         std           min  \
Numero de dedos    343.0  3.183673e+00    1.380131  1.000000e+00   
Angulo indice      343.0  5.582749e+01   55.053324  0.000000e+00   
Angulo corazon     343.0  6.942348e+01   76.194339  0.000000e+00   
Angulo anular      343.0  6.062354e+01   89.011941  0.000000e+00   
Angulo menique     343.0  5.277336e+01   98.354281  0.000000e+00   
Ancho pulgar       343.0  5.311584e-01    0.338302  1.132992e-01   
Ancho indice       343.0  4.148078e-01    0.323030  0.000000e+00   
Ancho corazon      343.0  3.053717e-01    0.324425  0.000000e+00   
Ancho anular       343.0  1.790547e-01    0.286787  0.000000e+00   
Ancho menique      343.0  1.171435e-01    0.253949  0.000000e+00   
Pulgar extendido   343.0  1.313994e+00    0.188971  9.000000e-01   
Indice extendido   343.0  1.150437e+00    0.474118  0.000000e+00   
Corazon extendido  343.0  8.408163e-01    0.645199  0.000000e+00   
Anular extendido   343.0  4.973761e-01    0.622172  0.000000e+00   
Menique extendido  343.0  3.338192e-01    0.571567  0.000000e+00   
Pulgar contraido   343.0  1.402529e+00    1.403254  2.540986e-02   
Indice contraido   343.0  9.146729e-01    0.947611  0.000000e+00   
Corazon contraido  343.0  7.527280e-01    0.953364  0.000000e+00   
Anular contraido   343.0  5.033762e-01    0.910933  0.000000e+00   
Menique contraido  343.0  4.440916e-01    1.072927  0.000000e+00   
Hu_1               343.0  2.663820e-01    0.052917  1.735964e-01   
Hu_2               343.0  3.172463e-02    0.025104  2.693973e-04   
Hu_3               343.0  2.603834e-03    0.003818  1.591417e-06   
Hu_4               343.0  5.551978e-04    0.001083  6.089869e-07   
Hu_5               343.0  2.141051e-06    0.000016 -1.034341e-05   
Hu_6               343.0  8.481699e-05    0.000283 -4.098032e-04   
Hu_7               343.0 -2.590974e-07    0.000004 -6.984006e-05   
Redondez           343.0  3.534590e-02    0.031097  3.159022e-03   
Compacidad         343.0  1.781646e+02  168.439532  1.941081e+01   
Clase              343.0  2.655977e+00    1.403218  1.000000e+00   

                            25%           50%           75%         max  
Numero de dedos    2.000000e+00  3.000000e+00  5.000000e+00    5.000000  
Angulo indice      1.873874e+01  3.387387e+01  7.675676e+01  262.342342  
Angulo corazon     0.000000e+00  4.864865e+01  1.104505e+02  337.657658  
Angulo anular      0.000000e+00  0.000000e+00  1.068468e+02  340.540541  
Angulo menique     0.000000e+00  0.000000e+00  8.684685e+01  352.432432  
Ancho pulgar       3.012243e-01  3.946897e-01  6.869694e-01    1.890679  
Ancho indice       2.402085e-01  3.580860e-01  5.066044e-01    2.175624  
Ancho corazon      0.000000e+00  2.643434e-01  4.508350e-01    1.793986  
Ancho anular       0.000000e+00  0.000000e+00  3.203323e-01    1.413057  
Ancho menique      0.000000e+00  0.000000e+00  1.362472e-01    1.347488  
Pulgar extendido   1.400000e+00  1.400000e+00  1.400000e+00    1.400000  
Indice extendido   9.000000e-01  1.400000e+00  1.400000e+00    1.400000  
Corazon extendido  0.000000e+00  1.400000e+00  1.400000e+00    1.400000  
Anular extendido   0.000000e+00  0.000000e+00  1.400000e+00    1.400000  
Menique extendido  0.000000e+00  0.000000e+00  9.000000e-01    1.400000  
Pulgar contraido   3.937720e-01  8.982826e-01  2.474390e+00    6.458996  
Indice contraido   2.139734e-01  7.429742e-01  1.023876e+00    5.572372  
Corazon contraido  0.000000e+00  4.590835e-01  9.320768e-01    5.237940  
Anular contraido   0.000000e+00  0.000000e+00  8.992156e-01    4.953476  
Menique contraido  0.000000e+00  0.000000e+00  9.347542e-02    5.450271  
Hu_1               2.265995e-01  2.605114e-01  2.986191e-01    0.480994  
Hu_2               1.220818e-02  2.706240e-02  4.581257e-02    0.154834  
Hu_3               4.949152e-04  1.371394e-03  2.728157e-03    0.033362  
Hu_4               6.582844e-05  1.846060e-04  5.546712e-04    0.014036  
Hu_5              -6.679299e-11  2.103928e-08  3.186376e-07 

In [324]:
# Creación de arreglo de características y variable de respuesta
target_column = ['Clase']

predictors = list(set(list(df.columns))-set(target_column))  #Lista con todos los encabezados menos 'diabetes'
df[predictors] = df[predictors]/df[predictors].max()
df.describe().transpose()

count      mean       std       min           25%  \
Numero de dedos    343.0  0.636735  0.276026  0.200000  4.000000e-01   
Angulo indice      343.0  0.212804  0.209853  0.000000  7.142857e-02   
Angulo corazon     343.0  0.205603  0.225656  0.000000  0.000000e+00   
Angulo anular      343.0  0.178022  0.261384  0.000000  0.000000e+00   
Angulo menique     343.0  0.149740  0.279073  0.000000  0.000000e+00   
Ancho pulgar       343.0  0.280935  0.178931  0.059925  1.593207e-01   
Ancho indice       343.0  0.190662  0.148477  0.000000  1.104090e-01   
Ancho corazon      343.0  0.170220  0.180840  0.000000  0.000000e+00   
Ancho anular       343.0  0.126714  0.202955  0.000000  0.000000e+00   
Ancho menique      343.0  0.086935  0.188461  0.000000  0.000000e+00   
Pulgar extendido   343.0  0.938567  0.134979  0.642857  1.000000e+00   
Indice extendido   343.0  0.821741  0.338656  0.000000  6.428571e-01   
Corazon extendido  343.0  0.600583  0.460857  0.000000  0.000000e+00   
Anular extendido   343.0  0.355269  0.444409  0.000000  0.000000e+00   
Menique extendido  343.0  0.238442  0.408262  0.000000  0.000000e+00   
Pulgar contraido   343.0  0.217144  0.217256  0.003934  6.096489e-02   
Indice contraido   343.0  0.164144  0.170055  0.000000  3.839898e-02   
Corazon contraido  343.0  0.143707  0.182011  0.000000  0.000000e+00   
Anular contraido   343.0  0.101621  0.183898  0.000000  0.000000e+00   
Menique contraido  343.0  0.081481  0.196858  0.000000  0.000000e+00   
Hu_1               343.0  0.553816  0.110017  0.360912  4.711071e-01   
Hu_2               343.0  0.204894  0.162135  0.001740  7.884664e-02   
Hu_3               343.0  0.078048  0.114442  0.000048  1.483463e-02   
Hu_4               343.0  0.039556  0.077179  0.000043  4.690056e-03   
Hu_5               343.0  0.007243  0.055678 -0.034993 -2.259679e-07   
Hu_6               343.0  0.019470  0.065075 -0.094073 -4.183942e-06   
Hu_7               343.0 -0.025120  0.406600 -6.771239 -1.892919e-03   
Redondez           343.0  0.218390  0.192139  0.019519  8.773694e-02   
Compacidad         343.0  0.179153  0.169374  0.019519  6.630707e-02   
Clase              343.0  2.655977  1.403218  1.000000  2.000000e+00   

                        50%       75%  max  
Numero de dedos    0.600000  1.000000  1.0  
Angulo indice      0.129121  0.292582  1.0  
Angulo corazon     0.144077  0.327108  1.0  
Angulo anular      0.000000  0.313757  1.0  
Angulo menique     0.000000  0.246421  1.0  
Ancho pulgar       0.208756  0.363345  1.0  
Ancho indice       0.164590  0.232855  1.0  
Ancho corazon      0.147350  0.251303  1.0  
Ancho anular       0.000000  0.226694  1.0  
Ancho menique      0.000000  0.101112  1.0  
Pulgar extendido   1.000000  1.000000  1.0  
Indice extendido   1.000000  1.000000  1.0  
Corazon extendido  1.000000  1.000000  1.0  
Anular extendido   0.000000  1.000000  1.0  
Menique extendido  0.000000  0.642857  1.0  
Pulgar contraido   0.139075  0.383092  1.0  
Indice contraido   0.133332  0.183741  1.0  
Corazon contraido  0.087646  0.177947  1.0  
Anular contraido   0.000000  0.181532  1.0  
Menique contraido  0.000000  0.017151  1.0  
Hu_1               0.541611  0.620838  1.0  
Hu_2               0.174783  0.295881  1.0  
Hu_3               0.041106  0.081774  1.0  
Hu_4               0.013153  0.039518  1.0  
Hu_5               0.000071  0.001078  1.0  
Hu_6               0.001941  0.015060  1.0  
Hu_7               0.000028  0.003734  1.0  
Redondez           0.151725  0.294366  1.0  
Compacidad         0.128644  0.222467  1.0  
Clase              2.000000  3.000000  6.0

In [353]:
# Creación de los conjuntos de entrenamiento y prueba

X = df[predictors].values
y = df[target_column].values

# 30% datos de prueba y 70% datos de entrenamiento
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.50, random_state = 40)
print(X_train.shape)
print(X_test.shape)

(171, 29)
(172, 29)


In [354]:
# Construcción, Predicción, y evaluación del modelo de red neuronal
# Se utiliza la función de activación lineal rectificada y un limite de 500 iteraciones

mlp = MLPClassifier(hidden_layer_sizes = (29,29,29), activation = 'relu', solver = 'adam', max_iter = 1000)
mlp.fit(X_train,y_train)
predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

c:\Users\metal\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1105: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [355]:
# Resultados de entrenamiento
print(confusion_matrix(y_train,predict_train))
print(classification_report(y_train,predict_train))

[[27  0  0  0  0  0]
 [ 0 67  0  0  0  0]
 [ 0  0 32  0  0  0]
 [ 0  0  0 21  0  0]
 [ 0  0  0  0 13  0]
 [ 0  0  0  0  0 11]]
              precision    recall  f1-score   support

         1.0       1.00      1.00      1.00        27
         2.0       1.00      1.00      1.00        67
         3.0       1.00      1.00      1.00        32
         4.0       1.00      1.00      1.00        21
         5.0       1.00      1.00      1.00        13
         6.0       1.00      1.00      1.00        11

    accuracy                           1.00       171
   macro avg       1.00      1.00      1.00       171
weighted avg       1.00      1.00      1.00       171



In [356]:
# Resultados de prueba
print(confusion_matrix(y_test,predict_test))
print(classification_report(y_test,predict_test))

[[11 15  5  5  1  4]
 [11 29 15  5  2  1]
 [ 2  9 10  5  1  1]
 [ 2  6  4  6  1  1]
 [ 0  1  3  3  4  1]
 [ 1  2  2  1  0  2]]
              precision    recall  f1-score   support

         1.0       0.41      0.27      0.32        41
         2.0       0.47      0.46      0.46        63
         3.0       0.26      0.36      0.30        28
         4.0       0.24      0.30      0.27        20
         5.0       0.44      0.33      0.38        12
         6.0       0.20      0.25      0.22         8

    accuracy                           0.36       172
   macro avg       0.34      0.33      0.33       172
weighted avg       0.38      0.36      0.36       172



Se utilizaron 55 muestras, de las cuales 25 eran diferentes a la pose a clasificar, es decir no eran 2 casos, por ello se observa la baja precisión en el test de prueba, ya que un perceptron no es bueno clasificando datos que no se puedan separar por un hiperplano ideal. En este caso los incorrectos están alejados entre sí, es decir hay varias clases.

Debido a la distribución de los datos, la normalización se hizo mediante el rango entre valores mínimos y máximos, de manera que los valores se atribuyan al valor de la fracción que ocupa en dicho rango.

Se le puede atribuir la buena precisión en los casos positivos, al numero de neuronas utilizadas en la capa oculta en este caso 87, siguiendo el ejemplo de la librería _sklearn_ donde asignan una neurona por cada dato del vector de características, sin embargo la sensibilidad es baja.

Al someter el algoritmo a la repetibilidad los resultados a diferencia del ejemplo inicial, cambian en un amplio espectro, esto quiere decir que las características no son las apropiadas, volviendo la red caótica, por tanto es conveniente hacer un análisis a las características extraídas.

Es preciso homogenizar correctamente los datos de entrada, ya que la aleatoriedad que maneja la librería *sklearn* es grupal es decir, toma conjuntos de datos y no individualmente.