### **Taller 6 -  Clasificación con RNA**

#### **Integrantes**

- Oscar Leonardo Riveros Perez

- Yovany Esneider Vargas Gutierrez 

**1. Estudiar el uso de Redes Neuronales en scikit-learn, haciendo énfasis en la función MLPClassifier**

**a. Machine Learning con redes neuronales usando scikit-learn y su func**

In [572]:
# Paso 1 - Carga de librerías y módulos necesarios
# Librerías
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import sklearn
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor
# Módulos
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, classification_report, confusion_matrix
from math import sqrt

In [573]:
# Paso 2 - Lectura de datos y comprobación
df = pd.read_csv('diabetes.csv')
print(df.shape)
df.describe().transpose()

(768, 9)


count        mean         std     min       25%       50%  \
pregnancies  768.0    3.845052    3.369578   0.000   1.00000    3.0000   
glucose      768.0  120.894531   31.972618   0.000  99.00000  117.0000   
diastolic    768.0   69.105469   19.355807   0.000  62.00000   72.0000   
triceps      768.0   20.536458   15.952218   0.000   0.00000   23.0000   
insulin      768.0   79.799479  115.244002   0.000   0.00000   30.5000   
bmi          768.0   31.992578    7.884160   0.000  27.30000   32.0000   
dpf          768.0    0.471876    0.331329   0.078   0.24375    0.3725   
age          768.0   33.240885   11.760232  21.000  24.00000   29.0000   
diabetes     768.0    0.348958    0.476951   0.000   0.00000    0.0000   

                   75%     max  
pregnancies    6.00000   17.00  
glucose      140.25000  199.00  
diastolic     80.00000  122.00  
triceps       32.00000   99.00  
insulin      127.25000  846.00  
bmi           36.60000   67.10  
dpf            0.62625    2.42  
age           41.00000   81.00  
diabetes       1.00000    1.00

In [574]:
# Paso 3 - Creación de arreglo de características y variable de respuesta
target_column = ['diabetes']
predictors = list(set(list(df.columns))-set(target_column))
df[predictors] = df[predictors]/df[predictors].max()
df.describe().transpose()

count      mean       std       min       25%       50%  \
pregnancies  768.0  0.226180  0.198210  0.000000  0.058824  0.176471   
glucose      768.0  0.607510  0.160666  0.000000  0.497487  0.587940   
diastolic    768.0  0.566438  0.158654  0.000000  0.508197  0.590164   
triceps      768.0  0.207439  0.161134  0.000000  0.000000  0.232323   
insulin      768.0  0.094326  0.136222  0.000000  0.000000  0.036052   
bmi          768.0  0.476790  0.117499  0.000000  0.406855  0.476900   
dpf          768.0  0.194990  0.136913  0.032231  0.100723  0.153926   
age          768.0  0.410381  0.145188  0.259259  0.296296  0.358025   
diabetes     768.0  0.348958  0.476951  0.000000  0.000000  0.000000   

                  75%  max  
pregnancies  0.352941  1.0  
glucose      0.704774  1.0  
diastolic    0.655738  1.0  
triceps      0.323232  1.0  
insulin      0.150414  1.0  
bmi          0.545455  1.0  
dpf          0.258781  1.0  
age          0.506173  1.0  
diabetes     1.000000  1.0

In [575]:
# Paso 4 - Creación de los conjuntos de entrenamiento y prueba

X = df[predictors].values
y = df[target_column].values

# 30% datos de prueba y 70% datos de entrenamiento
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30, random_state = 40)
print(X_train.shape)
print(X_test.shape)

(537, 8)
(231, 8)


In [576]:
# Paso 5 - Construcción, Predicción, y evaluación del modelo de red neuronal
# Se utiliza la función de activación lineal rectificada y un limite de 500 iteraciones

mlp = MLPClassifier(hidden_layer_sizes = (8,8,8), activation = 'relu', solver = 'adam', max_iter = 500)
mlp.fit(X_train,y_train)
predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

c:\Users\yovan\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1101: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\yovan\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(


In [577]:
# Resultados de entrenamiento
print(confusion_matrix(y_train,predict_train))
print(classification_report(y_train,predict_train))

[[316  42]
 [ 64 115]]
              precision    recall  f1-score   support

           0       0.83      0.88      0.86       358
           1       0.73      0.64      0.68       179

    accuracy                           0.80       537
   macro avg       0.78      0.76      0.77       537
weighted avg       0.80      0.80      0.80       537



In [578]:
# Resultados de prueba
print(confusion_matrix(y_test,predict_test))
print(classification_report(y_test,predict_test))

[[124  18]
 [ 39  50]]
              precision    recall  f1-score   support

           0       0.76      0.87      0.81       142
           1       0.74      0.56      0.64        89

    accuracy                           0.75       231
   macro avg       0.75      0.72      0.73       231
weighted avg       0.75      0.75      0.75       231



Las 2 medidas relevantes es la precisión y la Puntuación F1, esta ultima vide el desempeño entre la precisión y la sensibilidad (recall), lo ideal es que estás dos sean 1. Sin embargo, es difícil de obtener en escenarios del mundo real, por ahora la red neuronal formada por un perceptron multi capas (MLP), presenta un desempeño superior al 70%, sin embargo, presenta un mejor comportamiento en los casos negativos de diabetes.

**2. Clasificador, cuando son aplicadas al conjunto de vectores de características del proyecto**

Los datos a trabajar surgen de la extracción de 30 características, de las imágenes, sin embargo se somete a un análisis PCA para optimizar dicha base de datos, en este caso se reduce una dimensión y se añade un dato adicional el cual corresponde a el resultado esperado.

In [579]:
# Lectura de datos y comprobación
df = pd.read_csv('projectData.csv')
print(df.shape)
df.describe().transpose()

(55, 30)


count        mean           std         min        25%  \
Ángulo pulgar         55.0  136.261123  1.245602e+02   11.937567  49.951558   
Ángulo indice         55.0   45.795999  7.637928e+01  -82.129344 -11.513734   
Ángulo corazón        55.0   59.676815  5.732854e+01  -48.723547  24.800584   
Ángulo anular         55.0  -49.855185  4.042736e+01 -130.351368 -75.968095   
Ángulo meñique        55.0   12.699037  3.567101e+01  -60.895204  -4.630393   
Ancho pulgar          55.0    2.912917  1.030021e+00    0.498718   2.191746   
Ancho indice          55.0    0.103820  7.134631e-01   -1.815917  -0.246471   
Ancho corazón         55.0    0.657896  6.027326e-01   -1.197515   0.341799   
Ancho anular          55.0   -0.543795  5.208674e-01   -1.859325  -0.789444   
Ancho meñique         55.0    1.145319  4.827838e-01    0.192616   0.827618   
Pulgar extendido      55.0    0.738277  3.879838e-01    0.047237   0.444205   
Indice extendido      55.0   -0.130365  2.783657e-01   -0.721323  -0.368623   
Corazón extendido     55.0   -0.741374  2.530867e-01   -1.243457  -0.876336   
Anular extendido      55.0   -0.280734  2.210211e-01   -0.962652  -0.407295   
Meñique extendido     55.0    0.940815  2.105913e-01    0.577363   0.780319   
Pulgar contraído'     55.0   -1.063499  1.856823e-01   -1.363442  -1.183918   
'Indice contraído'    55.0   -0.026421  1.570055e-01   -0.385084  -0.123735   
'Corazón contraído'   55.0   -0.374873  1.404705e-01   -0.690932  -0.461248   
'Anular contraído     55.0    0.110513  1.206992e-01   -0.329019   0.043775   
Meñique contraído     55.0    0.125442  8.272812e-02   -0.029738   0.074856   
Numero de dedos'      55.0    0.392887  4.864409e-02    0.298493   0.350684   
'Hu_1'                55.0   -0.178677  4.694396e-02   -0.294331  -0.199788   
'Hu_2'                55.0    0.040091  1.102839e-02    0.012936   0.034144   
'Hu_3'                55.0   -0.093817  5.853408e-03   -0.108934  -0.097370   
'Hu_4'                55.0   -0.044675  2.039146e-03   -0.049721  -0.045675   
'Hu_5'                55.0    0.001738  3.831152e-04    0.000521   0.001578   
'Hu_6'                55.0    0.000282  4.040478e-05    0.000194   0.000252   
Hu_7                  55.0   -0.000007  1.905078e-06   -0.000011  -0.000009   
Redondez              55.0   -0.000004  7.293735e-07   -0.000006  -0.000005   
Chill                 55.0    0.545455  5.025189e-01    0.000000   0.000000   

                           50%         75%           max  
Ángulo pulgar        89.262272  169.243859  5.391594e+02  
Ángulo indice        25.204488   89.234847  3.231312e+02  
Ángulo corazón       45.690425   75.856029  2.788621e+02  
Ángulo anular       -50.161651  -27.332255  6.464447e+01  
Ángulo meñique        4.953059   27.688666  1.429132e+02  
Ancho pulgar          2.958085    3.719519  4.707844e+00  
Ancho indice          0.067871    0.306794  3.120244e+00  
Ancho corazón         0.600557    0.974753  2.455677e+00  
Ancho anular         -0.555083   -0.287717  7.585440e-01  
Ancho meñique         1.103161    1.443472  2.439145e+00  
Pulgar extendido      0.717579    0.963703  1.835821e+00  
Indice extendido     -0.088404    0.037490  5.505593e-01  
Corazón extendido    -0.733585   -0.587910  8.637041e-02  
Anular extendido     -0.244403   -0.145699  8.009188e-02  
Meñique extendido     0.922150    1.108907  1.413813e+00  
Pulgar contraído'    -1.092128   -0.988039 -6.086859e-01  
'Indice contraído'   -0.013339    0.096601  3.739617e-01  
'Corazón contraído'  -0.385995   -0.284152  2.240689e-03  
'Anular contraído     0.110773    0.184480  4.164240e-01  
Meñique contraído     0.118126    0.153907  3.787597e-01  
Numero de dedos'      0.396502    0.434156  4.822718e-01  
'Hu_1'               -0.184253   -0.150264 -5.099595e-02  
'Hu_2'                0.039217    0.046752  6.501571e-02  
'Hu_3'               -0.093334   -0.089246 -8.269632e-02  
'Hu_4'               -0.044470   -0.043498 -3.972266e-02  
'Hu_5'                0.001765    0.0

In [580]:
# Creación de arreglo de características y variable de respuesta
target_column = ['Chill']
predictors = list(set(list(df.columns))-set(target_column))
range = df[predictors].max() - df[predictors].min()
values =  df[predictors] - df[predictors].min()
df[predictors] = values/range # El método de normalizado cambia, al tener valores negativos
df.describe().transpose()

count      mean       std  min       25%       50%  \
Ángulo pulgar         55.0  0.235809  0.236258  0.0  0.072102  0.146664   
Ángulo indice         55.0  0.315662  0.188470  0.0  0.174247  0.264851   
Ángulo corazón        55.0  0.330907  0.175003  0.0  0.224442  0.288212   
Ángulo anular         55.0  0.412810  0.207324  0.0  0.278895  0.411238   
Ángulo meñique        55.0  0.361095  0.175022  0.0  0.276067  0.323089   
Ancho pulgar          55.0  0.573563  0.244711  0.0  0.402228  0.584294   
Ancho indice          55.0  0.388913  0.144538  0.0  0.317949  0.381630   
Ancho corazón         55.0  0.507888  0.164988  0.0  0.421361  0.492192   
Ancho anular          55.0  0.502520  0.198966  0.0  0.408684  0.498207   
Ancho meñique         55.0  0.424078  0.214902  0.0  0.282659  0.405312   
Pulgar extendido      55.0  0.386362  0.216922  0.0  0.221945  0.374789   
Indice extendido      55.0  0.464633  0.218861  0.0  0.277306  0.497624   
Corazón extendido     55.0  0.377555  0.190315  0.0  0.276067  0.383413   
Anular extendido      55.0  0.653965  0.211961  0.0  0.532592  0.688806   
Meñique extendido     55.0  0.434518  0.251768  0.0  0.242640  0.412203   
Pulgar contraído'     55.0  0.397404  0.246016  0.0  0.237856  0.359473   
'Indice contraído'    55.0  0.472518  0.206846  0.0  0.344313  0.489753   
'Corazón contraído'   55.0  0.455960  0.202649  0.0  0.331352  0.439914   
'Anular contraído     55.0  0.589626  0.161916  0.0  0.500097  0.589974   
Meñique contraído     55.0  0.379880  0.202518  0.0  0.256047  0.361971   
Numero de dedos'      55.0  0.513630  0.264688  0.0  0.283989  0.533301   
'Hu_1'                55.0  0.475288  0.192919  0.0  0.388530  0.452372   
'Hu_2'                55.0  0.521405  0.211760  0.0  0.407214  0.504637   
'Hu_3'                55.0  0.576169  0.223088  0.0  0.440758  0.594562   
'Hu_4'                55.0  0.504710  0.203945  0.0  0.404665  0.525193   
'Hu_5'                55.0  0.561015  0.176565  0.0  0.487273  0.573254   
'Hu_6'                55.0  0.541219  0.249147  0.0  0.354675  0.509937   
Hu_7                  55.0  0.362821  0.185729  0.0  0.249246  0.343142   
Redondez              55.0  0.515594  0.197931  0.0  0.377688  0.557178   
Chill                 55.0  0.545455  0.502519  0.0  0.000000  1.000000   

                          75%  max  
Ángulo pulgar        0.298368  1.0  
Ángulo indice        0.422849  1.0  
Ángulo corazón       0.380296  1.0  
Ángulo anular        0.528314  1.0  
Ángulo meñique       0.434643  1.0  
Ancho pulgar         0.765195  1.0  
Ancho indice         0.430033  1.0  
Ancho corazón        0.594622  1.0  
Ancho anular         0.600339  1.0  
Ancho meñique        0.556795  1.0  
Pulgar extendido     0.512397  1.0  
Indice extendido     0.596606  1.0  
Corazón extendido    0.492956  1.0  
Anular extendido     0.783464  1.0  
Meñique extendido    0.635476  1.0  
Pulgar contraído'    0.497383  1.0  
'Indice contraído'   0.634593  1.0  
'Corazón contraído'  0.586838  1.0  
'Anular contraído    0.688851  1.0  
Meñique contraído    0.449562  1.0  
Numero de dedos'     0.738185  1.0  
'Hu_1'               0.592053  1.0  
'Hu_2'               0.649308  1.0  
'Hu_3'               0.750373  1.0  
'Hu_4'               0.622414  1.0  
'Hu_5'               0.668164  1.0  
'Hu_6'               0.723623  1.0  
Hu_7                 0.458240  1.0  
Redondez             0.650846  1.0  
Chill                1.000000  1.0

In [581]:
# Creación de los conjuntos de entrenamiento y prueba

X = df[predictors].values
y = df[target_column].values

# 30% datos de prueba y 70% datos de entrenamiento
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30, random_state = 40)
print(X_train.shape)
print(X_test.shape)

(38, 29)
(17, 29)


In [582]:
# Construcción, Predicción, y evaluación del modelo de red neuronal
# Se utiliza la función de activación lineal rectificada y un limite de 500 iteraciones

mlp = MLPClassifier(hidden_layer_sizes = (29,29,29), activation = 'relu', solver = 'adam', max_iter = 1000)
mlp.fit(X_train,y_train)
predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

c:\Users\yovan\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1101: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [583]:
# Resultados de entrenamiento
print(confusion_matrix(y_train,predict_train))
print(classification_report(y_train,predict_train))

[[19  0]
 [ 0 19]]
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00        19
         1.0       1.00      1.00      1.00        19

    accuracy                           1.00        38
   macro avg       1.00      1.00      1.00        38
weighted avg       1.00      1.00      1.00        38



In [584]:
# Resultados de prueba
print(confusion_matrix(y_test,predict_test))
print(classification_report(y_test,predict_test))

[[6 0]
 [4 7]]
              precision    recall  f1-score   support

         0.0       0.60      1.00      0.75         6
         1.0       1.00      0.64      0.78        11

    accuracy                           0.76        17
   macro avg       0.80      0.82      0.76        17
weighted avg       0.86      0.76      0.77        17



Se utilizaron 55 muestras, de las cuales 25 eran diferentes a la pose a clasificar, es decir no eran 2 casos, por ello se observa la baja precisión en el test de prueba, ya que un perceptron no es bueno clasificando datos que no se puedan separar por un hiperplano ideal. En este caso los incorrectos están alejados entre sí, es decir hay varias clases.

Debido a la distribución de los datos, la normalización se hizo mediante el rango entre valores mínimos y máximos, de manera que los valores se atribuyan al valor de la fracción que ocupa en dicho rango.

Se le puede atribuir la buena precisión en los casos positivos, al numero de neuronas utilizadas en la capa oculta en este caso 87, siguiendo el ejemplo de la librería _sklearn_ donde asignan una neurona por cada dato del vector de características, sin embargo la sensibilidad es baja.

Al someter el algoritmo a la repetibilidad los resultados a diferencia del ejemplo inicial, cambian en un amplio espectro, esto quiere decir que las características no son las apropiadas, volviendo la red caótica, por tanto es conveniente hacer un análisis a las características extraídas.

Es preciso homogenizar correctamente los datos de entrada, ya que la aleatoriedad que maneja la librería *sklearn* es grupal es decir, toma conjuntos de datos y no individualmente.